import type { Metadata } from "next";
import "./globals.css";
import { LanguageProvider } from "./_components/LanguageContext";


import Script from "next/script";
import { AuthProvider } from "./_components/AuthProviderContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className=""
      >
        {/* Hidden dropdown */}
        <div id="google_translate_element" style={{ display: "hidden" }}></div>

        {/* Google Translate Init Script */}
        <Script id="google-translate-init" strategy="afterInteractive">
          {`
    function googleTranslateElementInit() {
      new google.translate.TranslateElement({
        pageLanguage: 'sv',
        includedLanguages: 'en,sv,ar',
        autoDisplay: false
      }, 'google_translate_element');
    }
  `}
        </Script>

        {/* Google Translate External JS */}
        <Script
          src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          strategy="afterInteractive"
        />
        <AuthProvider>
          <LanguageProvider>
            <div id="google_translate_element"></div>
            {children}
          </LanguageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
